name: 13 workflow
on: [workflow_dispatch]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node_modules
        id: cashe-step
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: "cache-file"
      - name: Display cashe
        run: echo '${{ toJSON(steps.cashe-step.outputs) }}'
      - name: Install node_modules
        run: npm install
