name: 14 workflow
on: [workflow_dispatch]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Math expression
        run: expr 2 + 2 > math-result.txt
      - name: Upload result file
        uses: actions/upload-artifact@v4
        with:
          name: math-result
          path: math-result.txt
  second-job:
    runs-on: ubuntu-latest
    needs: run-first-command
    steps:
      - name: Download file
        uses: actions/download-artifact@v4
        with:
          name: math-result
      - name: Print file
        run: |
          value='cat math-result.txt'
          echo $value