name: 5 workflow
on: 
  workflow_dispatch:
    inputs:
      titleCustom:
        description: Type the title
        type: string
        required: true
        default: "Hello world!"

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display EVENTS var
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
