name: 8 workflow
on: 
  workflow_dispatch:
    inputs:
      titleCustom:
        description: Type the title
        type: string
        required: true
        default: "Hello world!"
      selectCustom:
        description: Select Value
        type: choice
        required: true
        options:
          - Value 1
          - Value 2
          - Value 3
          - Value 4
        default: "Value 2"
      checkCustom:
        description: Checkbox
        type: boolean
        required: false


jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display EVENTS var
        run: |
          echo "Title: ${{ inputs.titleCustom }}"
          echo "Title: ${{ inputs.selectCustom }}"
          echo "Title: ${{ inputs.checkCustom }}"
