name: Test concurrency
on: [workflow_dispatch]
concurrency: 
  group: concurrency-test
  cancel-in-progress: true
jobs:
  test-timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Some step
        run: sleep 50