name: Fourth workflow
on:
  workflow_run:
    workflows: [Third workflow]
    types:
      - completed

jobs:
  success-command:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Print hello
        run: echo "Hello success"
  fail-command:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Print hello
        run: echo "Hello Fail"