name: Second workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display node version Ubuntu
        run: node -v
  run-parallel-comand:
    runs-on: windows-latest
    steps:
      - name: Display node version Windows
        run: node -v
  run-second-command:
    runs-on: macos-latest
    needs: [run-first-command]
    steps:
      - name: Display node version MacOs
        run: node -v