name: Third workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Ls files and copy Repo
        run: ls -a
      - uses: actions/checkout@v4
      - name: Ls files
        run: ls -a